### ISSUE TITLE
question

### ISSUE THREAD

**Issue by dkwo** [davmac314/elf2efi#1]
Can this be used when building a unified kernel image?
Currentluy I use
```
llvm-objcopy \
	--add-section .osrel="/etc/os-release" \
	--set-section-flags .osrel=data,readonly \
	--add-section .cmdline="${tmpdir}/cmdline" \
	--set-section-flags .cmdline=data,readonly \
	--add-section .initrd="${tmpdir}/unified-initram" \
	--set-section-flags .initrd=code,readonly \
	--add-section .linux="${KERNEL}" \
	--set-section-flags .linux=code,readonly \
	"${efistub}" "${EFI}/${UKI}"
```
and I wonder if I can replace `llvm-objcopy` with `elf2efi`.
Thanks.

**Comment by davmac314** [comment]
It looks like you are using `llvm-objcopy`'s `--add-section` flag to include sections from file contents.

elf2efi converts an ELF file to PE format, it doesn't have any capability to add sections from contents.

**Comment by dkwo** [comment]
I see, thanks for explaining.
